apiVersion: v1
kind: Secret
metadata:
  name: james-secret
type: Opaque
data:
  URL: {{ .Values.url | b64enc | quote }}
  ADMIN_TOKEN: {{ .Values.adminToken | b64enc | quote }}
  HTTP_PORT: {{ .Values.httpPort | b64enc | quote }}