image: shn27/james-load-testing:shn27-addSendMail_linux_amd64
reqPerSecond: 5
runForMinutes: 60
memberPerGroup: 20

url: "http://inbox-server-admin.ace.svc"
adminToken: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDI5NTUxMzQ2LCJwZXJtaXNzaW9ucyI6eyJwZXJtLmFkZHJlc3MuZ3JvdXBzLioiOlsiR0VUIiwiUE9TVCIsIkRFTEVURSJdLCJwZXJtLmFkZHJlc3MuZ3JvdXBzLiouKiI6WyJQVVQiLCJERUxFVEUiXX0sInN1YiI6InVzciZhZG1pbiQyQGNsb3VkLmFwcHNjb2RlLmNvbSIsInR5cGUiOiJhZG1pbiJ9.LEHdZ07qjsLaPEAbfdpRY1aq6KDQCJ9z6PkY6QxpcWprAKs4jQu365uqHuMYVxmdauVpoFGaAhs8a_WlGbq8voEzRevxdq6imGQZp0I_F8hnJyBigxDEeDJpEUeCbGUjPWK_FVxzlQtnjzxoqaVPt9NA73szStdEXzNeeX7KjVKWPbLh5WN0hUoHmxazYiBPitsu0IUEbcSQs-sN5Yl_hQjhYhCFi7qmcDSv8vwlKoydzMi93PFLCvuH5pJfpAALzzs2bwcHzPDjM-KhfdhV7AvU87dJBCzh8VzivCoNWXjA5P0EpGN7bkpvLmz3kifSEuUPU_SCX5fTNrPUpVqOag"
httpPort: "8000"
